[#Smart05]: Julian Smart. *Cross-Platform GUI Programming with wxWidgets*. Prentice Hall, 2005.
[#Chen07]: Raymond Chen. *The Old New Thing: Practical Development Throughout the Evolution of Windows*. Addison-Wesley Professional, 2007.
[#Foley95]: James D Foley. *Computer Graphics: Principles and Practice in C*. Addison-Wesley Professional, 1995