[]: glossary: aplicatie
	Orice componenta software care necesita interactiunea utilizatorului pentru desfasurarea actiunii.

[]: glossary: aplicatie nativa
	Aplicatie care ruleaza deasupra sistemului de operare avand acces direct la resursele hardware si interfata sistemului de operare. Aplicatiile native necesita instalare.

[]: glossary: aplicatie web
	O pagina web prezentata (deschisa) de un browser care ofera un serviciu utilizatorului. Aplicatiile web se aseamana cu aplicatiile native in functionalitate dar difera prin modul in care acestea sunt dispuse utilizatorului.