latex input:		mmd-article-header  
Title:				wxStyle Documentation  
Author:				Pana Alexandru  
Base Header Level:	2  
latex mode:			memoir  
latex input:		mmd-natbib-plain
latex input:		mmd-article-begin-doc  
latex footer:		mmd-memoir-footer  
